### ISSUE TITLE
Unable to enable mode due to svg-lib error 

### ISSUE THREAD

**Issue by Skosulor** [rougier/org-margin#1]
Config:
``` 
    (use-package svg-lib)
    (straight-use-package
      '(org-margin :type git :host github :repo "rougier/org-margin))
```
Enabling org-margin mode with M-x results in the following error:

> svg-lib-tag: Wrong type argument: listp, org-level-1

**Comment by rougier** [comment]
I just added a commit to remove svg dependency.
