### ISSUE TITLE
 (void-function imagep) when open the org-margin mode

### ISSUE THREAD

**Issue by zhanyi22333** [rougier/org-margin#3]
Here is the all info in Backtrace:
```emacs-lisp
Debugger entered--Lisp error: (void-function imagep)
  (imagep item)
  (cond ((imagep item) (truncate (car (image-size item)))) ((stringp item) (length item)) (t 0))
  (closure ((header-set #("H1" 0 2 (face (font-lock-comment-face default))) #("H2" 0 2 (face (font-lock-comment-face default))) #("H3" 0 2 (face (font-lock-comment-face default))) #("H4" 0 2 (face (font-lock-comment-face default))) #("H5" 0 2 (face (font-lock-comment-face default))) #("H6" 0 2 (face (font-lock-comment-face default)))) t) (item) (cond ((imagep item) (truncate (car (image-size item)))) ((stringp item) (length item)) (t 0)))(#("H1" 0 2 (face (font-lock-comment-face default))))
  mapcar((closure ((header-set #("H1" 0 2 (face (font-lock-comment-face default))) #("H2" 0 2 (face (font-lock-comment-face default))) #("H3" 0 2 (face (font-lock-comment-face default))) #("H4" 0 2 (face (font-lock-comment-face default))) #("H5" 0 2 (face (font-lock-comment-face default))) #("H6" 0 2 (face (font-lock-comment-face default)))) t) (item) (cond ((imagep item) (truncate (car (image-size item)))) ((stringp item) (length item)) (t 0))) (#("H1" 0 2 (face (font-lock-comment-face default))) #("H2" 0 2 (face (font-lock-comment-face default))) #("H3" 0 2 (face (font-lock-comment-face default))) #("H4" 0 2 (face (font-lock-comment-face default))) #("H5" 0 2 (face (font-lock-comment-face default))) #("H6" 0 2 (face (font-lock-comment-face default)))))
  (let* ((header-set (cdr (assoc org-margin-headers-set org-margin-headers))) (header-widths (mapcar #'(lambda (item) (cond (... ...) (... ...) (t 0))) header-set)) (marker-widths (mapcar #'(lambda (item) (let (...) (cond ... ... ...))) org-margin-markers)) (max-width (max (apply #'max header-widths) (apply #'max marker-widths))) (max-level (min org-margin-max-level (length header-set))) (keyword (format "^\\(\\*\\{1,%s\\} \\)" max-level))) (set (make-local-variable 'org-margin--left-margin-width) left-margin-width) (set-window-margins (selected-window) (1+ max-width)) (set (make-local-variable 'left-margin-width) (1+ max-width)) (set (make-local-variable 'org-margin--font-lock-keywords) font-lock-keywords) (if (> max-level 0) (progn (font-lock-add-keywords nil (list (cons keyword (cons 1 (cons ... ...))))))))
  org-margin-mode-on()
  (if org-margin-mode (org-margin-mode-on) (org-margin-mode-off))
  (let ((last-message (current-message))) (setq org-margin-mode (cond ((eq arg 'toggle) (not org-margin-mode)) ((and (numberp arg) (< arg 1)) nil) (t t))) (if (boundp 'local-minor-modes) (progn (setq local-minor-modes (delq 'org-margin-mode local-minor-modes)) (if org-margin-mode (progn (setq local-minor-modes (cons 'org-margin-mode local-minor-modes)))))) (if org-margin-mode (org-margin-mode-on) (org-margin-mode-off)) (run-hooks 'org-margin-mode-hook (if org-margin-mode 'org-margin-mode-on-hook 'org-margin-mode-off-hook)) (if (called-interactively-p 'any) (progn nil (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local " in current buffer")) (message "Org-Margin mode %sabled%s" (if org-margin-mode "en" "dis") local))))))
  org-margin-mode(1)
  eval((org-margin-mode 1) nil)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nThis commands handles `defvar', `defcustom' and `defface' the\nsame way that `eval-defun' does.  See the doc string of that\nfunction for details.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode -0x1c682929fbb38247>)(nil)
  apply(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nThis commands handles `defvar', `defcustom' and `defface' the\nsame way that `eval-defun' does.  See the doc string of that\nfunction for details.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode -0x1c682929fbb38247>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by rougier** [comment]
`(void-function imagep)` is really a weird error since it comes from emacs and is pretty standard. What is your emacs version ? Can you try `C-h f RET imagep` ?

(I've edited your post by adding 3 backsticks at start and end to format code)

**Comment by zhanyi22333** [comment]
C-h f can not find imagep in my emacs.

Here is my Emacs version infomation:
GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2022-09-15.

**Comment by rougier** [comment]
Weird. Can you try adding `(require 'image)` (or load it manually)?

**Comment by zhanyi22333** [comment]
I try (require 'image) many times and find a wired behavior. It always show 'image' in echo area. It just not behavior like other package that show 'nil' for requires  after the first require.

Where to download the image.el?  I want to load it manually but the search engine not show anything relevant.

**Comment by zhanyi22333** [comment]
I find the image.el.gz in Contents/Resources/lisp. I'm sure there is no imagep function defination in this file.

**Comment by rougier** [comment]
Can you open an image with emacs? Does it show the image?

**Comment by zhanyi22333** [comment]
Yes, I can open an image in org mode.

**Comment by rougier** [comment]
Can you evaluate `(fboundp 'imagep)`?

**Comment by zhanyi22333** [comment]
The evaluation of (fboundp 'imagep) return nil.

**Comment by zhanyi22333** [comment]
I find a function named `image-jpeg-p` in file _image.el.gz_ . Does it have some relationship with `imagep`?

**Comment by rougier** [comment]
Maybe you can use:
```emacs-lisp
(defun imagep (image)
  (eq (car image) 'image))
```

**Comment by zhanyi22333** [comment]
It produces the below error:
`eq: Wrong type argument: listp, #("H1" 0 2 (face (font-lock-comment-face default)))`
It seems a string with properties.

Here is the backtrace:

Debugger entered--entering a function:
* imagep(#("H1" 0 2 (face (font-lock-comment-face default))))
  (cond ((imagep item) (truncate (car (image-size item)))) ((stringp item) (length item)) (t 0))
  (closure ((header-set #("H1" 0 2 (face (font-lock-comment-face default))) #("H2" 0 2 (face (font-lock-comment-face default))) #("H3" 0 2 (face (font-lock-comment-face default))) #("H4" 0 2 (face (font-lock-comment-face default))) #("H5" 0 2 (face (font-lock-comment-face default))) #("H6" 0 2 (face (font-lock-comment-face default)))) t) (item) (cond ((imagep item) (truncate (car (image-size item)))) ((stringp item) (length item)) (t 0)))(#("H1" 0 2 (face (font-lock-comment-face default))))
  mapcar((closure ((header-set #("H1" 0 2 (face (font-lock-comment-face default))) #("H2" 0 2 (face (font-lock-comment-face default))) #("H3" 0 2 (face (font-lock-comment-face default))) #("H4" 0 2 (face (font-lock-comment-face default))) #("H5" 0 2 (face (font-lock-comment-face default))) #("H6" 0 2 (face (font-lock-comment-face default)))) t) (item) (cond ((imagep item) (truncate (car (image-size item)))) ((stringp item) (length item)) (t 0))) (#("H1" 0 2 (face (font-lock-comment-face default))) #("H2" 0 2 (face (font-lock-comment-face default))) #("H3" 0 2 (face (font-lock-comment-face default))) #("H4" 0 2 (face (font-lock-comment-face default))) #("H5" 0 2 (face (font-lock-comment-face default))) #("H6" 0 2 (face (font-lock-comment-face default)))))
  (let* ((header-set (cdr (assoc org-margin-headers-set org-margin-headers))) (header-widths (mapcar #'(lambda (item) (cond (... ...) (... ...) (t 0))) header-set)) (marker-widths (mapcar #'(lambda (item) (let (...) (cond ... ... ...))) org-margin-markers)) (max-width (max (apply #'max header-widths) (apply #'max marker-widths))) (max-level (min org-margin-max-level (length header-set))) (keyword (format "^\\(\\*\\{1,%s\\} \\)" max-level))) (set (make-local-variable 'org-margin--left-margin-width) left-margin-width) (set-window-margins (selected-window) (1+ max-width)) (set (make-local-variable 'left-margin-width) (1+ max-width)) (set (make-local-variable 'org-margin--font-lock-keywords) font-lock-keywords) (if (> max-level 0) (progn (font-lock-add-keywords nil (list (cons keyword (cons 1 (cons ... ...))))))))
  org-margin-mode-on()
  (if org-margin-mode (org-margin-mode-on) (org-margin-mode-off))
  (let ((last-message (current-message))) (setq org-margin-mode (cond ((eq arg 'toggle) (not org-margin-mode)) ((and (numberp arg) (< arg 1)) nil) (t t))) (if (boundp 'local-minor-modes) (progn (setq local-minor-modes (delq 'org-margin-mode local-minor-modes)) (if org-margin-mode (progn (setq local-minor-modes (cons 'org-margin-mode local-minor-modes)))))) (if org-margin-mode (org-margin-mode-on) (org-margin-mode-off)) (run-hooks 'org-margin-mode-hook (if org-margin-mode 'org-margin-mode-on-hook 'org-margin-mode-off-hook)) (if (called-interactively-p 'any) (progn nil (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local " in current buffer")) (message "Org-Margin mode %sabled%s" (if org-margin-mode "en" "dis") local))))))
  org-margin-mode(1)
  eval((org-margin-mode 1) nil)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nThis commands handles `defvar', `defcustom' and `defface' the\nsame way that `eval-defun' does.  See the doc string of that\nfunction for details.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode -0x1c682929fbb38247>)(nil)
  apply(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nThis commands handles `defvar', `defcustom' and `defface' the\nsame way that `eval-defun' does.  See the doc string of that\nfunction for details.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode -0x1c682929fbb38247>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by rougier** [comment]
Sorry, another try:

```emacs-lisp
(defun imagep (image)
  (and (consp image) (eq (car image) 'image)))
```

**Comment by zhanyi22333** [comment]
Thanks. It works good!
